name: PipelineWorkflow

on:
  push:
    branches:
      - child_Branch2
   pull_request:
     branches:
       - child_Branch2

jobs:
    build:
        name: Azure Pipeline
        runs-on: windows-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/khanDevOps/Project_Agile
            azure-pipeline-name: 'WB'
            azure-devops-token: ${{ secrets.AZURE_SECRETS}}